name: theme
description: "White-label branding system with dynamic theme support"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.38.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  preference_manager:
    path: ../preference_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
