final Map<String, String> de = {
  // Splash
  'splash_welcome_title': 'Herzlich Willkommen',
  'splash_welcome_subtitle': 'Bei {appName}.',
  'splash_personalize_title': 'Erlebnis personalisieren',
  'splash_personalize_description': 'Mit ein paar kurzen Fragen vorab erhältst du zu deinen Interessen und deinem Wohnort passende Vorschläge.',
  'splash_personalize_action': 'Jetzt personalisieren',
  'splash_create_account_title': 'Konto anlegen',
  'splash_create_account_description': 'Lege gleich ein Konto an, merke dir die spannendsten Events und verpasse kein Ereignis in deiner Nähe.',
  'splash_create_account_action': 'Jetzt Konto anlegen',

  // Location onboarding
  'loc_onboarding_back': 'Zurück',
  'loc_onboarding_title': 'Ort auswählen',
  'loc_onboarding_subtitle': 'Für welches Gebiet sollen wir dir Vorschläge machen? ',
  'loc_onboarding_confirm_button': 'Auswahl bestätigen',

  // Auth
  'back': 'Zurück',
  'auth_signin_title': 'Anmelden',
  'auth_signin_no_account': 'Sie haben noch kein Konto? ',
  'auth_signin_create_account': 'Benutzerkonto erstellen',
  'auth_signin_username_or_email_label': 'Benutzername oder E-Mail',
  'auth_signin_username_or_email_hint': 'Benutzername oder E-Mail-Adresse',
  'auth_password_label': 'Passwort',
  'auth_password_hint': 'Passwort',
  'auth_signin_button': 'Anmelden',
  'auth_signup_title': 'Konto erstellen',
  'auth_signup_have_account': 'Du hast bereits ein Konto? ',
  'auth_signup_signin': 'Anmelden',
  'auth_signup_username_label': 'Benutzername',
  'auth_signup_username_hint': 'Benutzername',
  'auth_signup_email_label': 'E-Mail',
  'auth_signup_email_hint': 'E-Mail-Adresse',
  'auth_signup_confirm_password_label': 'Passwort bestätigen',
  'auth_signup_confirm_password_hint': 'Passwort bestätigen',
  'auth_signup_button': 'Konto erstellen',

  // Validation Errors
  'error_field_required': 'Dieses Feld ist erforderlich',
  'error_invalid_email': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
  'error_username_too_short': 'Benutzername muss mindestens 6 Zeichen lang sein',
  'error_username_too_long': 'Benutzername darf 15 Zeichen nicht überschreiten',
  'error_username_no_spaces': 'Benutzername darf keine Leerzeichen enthalten',
  'error_username_lowercase_only': 'Benutzername darf nur Kleinbuchstaben und Unterstriche enthalten',
  'error_password_too_short': 'Passwort muss mindestens 8 Zeichen lang sein',
  'error_password_no_spaces': 'Passwort darf keine Leerzeichen enthalten',
  'error_passwords_dont_match': 'Passwörter stimmen nicht überein',
  'error_invalid_name': 'Name darf nur Buchstaben, Leerzeichen, Bindestriche und Apostrophe enthalten',
  'error_invalid_phone': 'Bitte geben Sie eine gültige Telefonnummer ein',
  'error_invalid_website': 'Bitte geben Sie eine gültige Website-URL ein',

  // Onboarding - Welcome Page
  'welcome_header': 'Moin, in der',
  'onboarding_title_1': 'App - Egal, ob zu Besuch oder zu Hause, dein',
  'onboarding_title_2': '{appName} Gefühl',
  'onboarding_title_3': 'beginnt genau hier – personalisiert und voller Inspiration.',
  'splash_title': 'Finde dein nächstes\nErlebnis mit',
  'welcome_button': 'Los geht\'s!',
  'next': 'weiter',
  'finish': 'Fertig!',

  // Onboarding - User Type Selection
  'user_type_selection_title': 'Das passt mehr zu mir:',
  'user_type_home': 'Ich bin hier zu \nHause.',
  'user_type_home_info': 'Wähle dies, wenn du dich registrieren möchtest. Dann kannst du auch Favoriten speichern.',
  'user_type_guest': 'Ich bin hier zu \nGast.',
  'user_type_guest_info': 'Wähle dies, wenn du ohne Registrierung fortfahren und daher keine Favoriten speichern möchtest. Du kannst dich später über die Einstellungen registrieren.',
  'user_type_home_card_label': 'Benutzertyp als Bewohner auswählen, mit einer Illustration eines Hauses.',
  'user_type_guest_card_label': 'Benutzertyp als Gast auswählen, mit einer Illustration eines Koffers.',

  // Onboarding - Auth Page
  'registration_title': 'kann mehr!',
  'password_reset_title': 'Passwort vergessen',
  'login_subtitle': 'Melde dich bei {appId} an und passe die App an deine Bedürfnisse an.',
  'registration_subtitle': 'Registriere dich für {appId} und personalisiere die App nach deinen Bedarfen.',
  'reset_link_send': 'Passwort-Zurücksetzungs-E-Mail gesendet',
  'login_email_label': 'Deine E-Mail',
  'register_email_label': 'Deine E-Mail',
  'reset_password_email_label': 'Deine E-Mail',
  'login_password_label': 'Passwort eingeben',
  'register_password_label': 'Sicheres Passwort festlegen',
  'login_email_validation_empty': 'Bitte geben Sie eine E-Mail-Adresse ein',
  'login_email_validation_invalid': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
  'login_password_validation_empty': 'Bitte Passwort eingeben',
  'register_email_validation_empty': 'Bitte geben Sie eine E-Mail-Adresse ein',
  'register_password_validation_empty': 'Bitte Passwort eingeben',
  'clear_email_tooltip': 'E-Mail löschen',
  'hide_password_tooltip': 'Passwort verbergen',
  'show_password_tooltip': 'Passwort anzeigen',
  'login_no_account_register': 'Du hast noch kein Konto? Hier registrieren.',
  'login_already_registered_login': 'Bereits registriert? Hier anmelden',
  'remember_password_login_again': 'Passwort merken? Erneut anmelden',
  'page_count_label': 'Aktuelle Seite von Gesamtseiten',
  'back_button_label': 'Zurück',

  // Onboarding
  'location_onboarding_sub_text': 'Für welches Gebiet sollen wir dir Vorschläge machen?',
  'select_location': 'Ort auswählen',
  'perimeter': 'Umkreis',
  'choose_your_location': 'Wähle deinen Ort aus',
  'confirm_location': 'Auswahl bestätigen',
  'swipe_to_start_quickly': 'Swipen um schnell zu Starten',

  // Profile sheet
  'profile': 'Profil',
  'add': 'Hinzufügen',
  'favorites': 'Favoriten',
  'organizer': 'Veranstalter',
  'interests': 'Interessen',
  'your_location': 'Dein Ort',
  'settings': 'Einstellungen',
  'faq': 'Häufige Fragen',
  'privacy': 'Datenschutz',
  'share_app': 'App mit andern teilen',
  'legal': 'Rechtliches',
  'log_out': 'Abmelden',

  // Settings sheet
  'edit_profile': 'Profil bearbeiten',
  'login_security': 'Log-in & Sicherheit',
  'accessibility': 'Barrierefreiheit',
  'dark_mode': 'Dunkler Modus',
  'delete_account': 'Account löschen',

  // Calendar
  'calendar_cancel': 'Abbrechen',
  'calendar_confirm_range': 'Zeitraum auswählen',
  'calendar_weekday_mo': 'Mo',
  'calendar_weekday_tu': 'Di',
  'calendar_weekday_we': 'Mi',
  'calendar_weekday_th': 'Do',
  'calendar_weekday_fr': 'Fr',
  'calendar_weekday_sa': 'Sa',
  'calendar_weekday_su': 'So',
  'calendar_month_jan': 'Januar',
  'calendar_month_feb': 'Februar',
  'calendar_month_mar': 'März',
  'calendar_month_apr': 'April',
  'calendar_month_may': 'Mai',
  'calendar_month_jun': 'Juni',
  'calendar_month_jul': 'Juli',
  'calendar_month_aug': 'August',
  'calendar_month_sep': 'September',
  'calendar_month_oct': 'Oktober',
  'calendar_month_nov': 'November',
  'calendar_month_dec': 'Dezember',

  // Info
  'find_next_experience': 'Finde dein nächstes Erlebnis in {appCityName}',
  'search': 'Suchen',
  'no_data': 'Keine Daten',
  'no_listings': 'Keine Einträge verfügbar',
  'error_loading': 'Fehler beim Laden',
  'error_server_unavailable': 'Dienst nicht verfügbar. Bitte versuche es später erneut.',
  'see_all': 'Alle anzeigen',
  'nearby': 'In der Nähe',
  'show_all': 'Alle anzeigen',
  'comming_soon': 'Demnächst verfügbar',

  // Parking
  'parking': 'Parken',
  'free': 'Frei ',
  'total': 'Gesamt :',
  'no_parking_data_text': 'Keine Parkdaten verfügbar',
  'open_maps': 'Karte öffnen',
  'navigation_start': 'Navigation starten',

  // Profile / Account
  'profile_update_success': 'Profil erfolgreich aktualisiert',
  'submit': 'Absenden',
  'account_section_title': 'KONTO',
  'account_header': 'mein.{appNameShort}',
  'account_my_profile': 'Mein Profil',
  'my_profile_data': 'MEINE PROFILDATEN',
  'first_name': 'Vorname',
  'last_name': 'Nachname',
  'account_settings_contact': 'Einstellungen & Kontakt',
  'account_favorites_title': 'MEINE FAVORITEN',
  'no_fav_listing': 'Keine Favoritenlisten',
  'dashboard_logout': 'Abmelden',
  'register_login': 'Registrieren / Anmelden',
  'logout_confirmation_message': 'Bist du sicher, dass du dich abmelden möchtest?',
  'delete_account_confirmation': 'Konto löschen Bestätigung',
  'delete_account_message': 'Bist du sicher, dass du dein Konto löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.',
  'cancel': 'Abbrechen',
  'ok': 'OK',
  'delete': 'Löschen',

  // Settings Screen
  'setting': 'Einstellungen',
  'language': 'Sprache',
  'notifications': 'Benachrichtigungen',
  'app_theme': 'Designanpassungen',
  'reset_password': 'Passwort zurücksetzen',
  'terms_of_use': 'Nutzungsbedingungen',

  // Terms & Conditions screen
  'terms_and_conditions_title': 'Bevor es losgeht, akzeptiere bitte \n unsere Nutzungsbedingungen  und Datenschutzhinweise.',
  'terms_and_conditions_subtitle': 'Ohne Zustimmung kannst du die {appId}-App leider nicht nutzen.',
  'view_terms_and_conditions': 'Nutzungsbedingungen anzeigen',
  'accept_terms_and_conditions': 'Ich habe die Bedingungen gelesen und akzeptiere sie.',
  'next_button': 'weiter',
  'finish_button': 'Fertig!',

  // Push Notifications screen
  'push_notifications_title': 'Die {appId} App sendet dir \nMitteilungen zu Events in deiner Nähe, \nerinnert dich an gespeicherte \nVeranstaltungen und macht dich auf \nlokale Highlights aufmerksam.',
  'push_notifications_subtitle': 'Bitte bestätige, dass du mit derartigen \nPush-Nachrichten einverstanden bist.',
  'accept_push_notifications': 'Ich möchte bei für mich wichtigen Infos benachrichtigt werden.',
  'decline_push_notifications': 'Ich möchte keine Push-Benachrichtigungen erhalten.',
  'notification': 'Benachrichtigung',
  'push_notification': 'Push-Benachrichtigung',
  'notification_service_disabled': 'Der Benachrichtigungsdienst ist für diese App nicht verfügbar.',

  // Newsletter screen
  'newsletter_title': 'Mit dem Abbonieren unseres Newsletters erhältst du regelmäßig kuratierte Updates, Stadtnachrichten und ausgewählte Veranstaltungsinformationen direkt in deiner Mail.',
  'newsletter_permission': 'Möchtest du auf dem Laufenden bleiben? Aboniere unseren Newsletter!',
  'newsletter': 'Abonniere den Newsletter',
  'subscribe': 'Abonnieren',
  'subscribe_request_sent': 'Abonnementanfrage erfolgreich gesendet.',
  'privacy_policy': 'Datenschutzrichtlinie',
  'view_privacy_policy': 'Datenschutzhinweise anzeigen',
  'imprint': 'Impressum',
  'bright': 'Hell',
  'dark': 'Dunkel',

  // Listings
  'listingTitle': 'Einträge',
  'noResults': 'Keine Ergebnisse gefunden',
  'errorTitle': 'Etwas ist schiefgelaufen',
  'retryButton': 'Erneut versuchen',
  'description': 'Beschreibung',
  'contactInfo': 'Kontaktinformationen',
  'eventInfo': 'Veranstaltungsinfo',
  'tags': 'Tags',
  'startDate': 'Startdatum',
  'endDate': 'Enddatum',
  'phone': 'Telefon',
  'email': 'E-Mail',
  'website': 'Webseite',
  'no_languages_available': 'Keine Sprachen verfügbar',

  // Date filter
  'f_by_date': 'Nach Datum filtern',
  'start_date': 'Startdatum',
  'end_date': 'Enddatum',
  'quick_ranges': 'Schnellauswahl',
  'l_7d': 'Nächste 7 Tage',
  'l_30d': 'Nächste 30 Tage',
  't_month': 'Diesen Monat',
  'not_set': 'Nicht gesetzt',
  'select': 'Auswählen',
  'reset': 'Zurücksetzen',
  'apply': 'Anwenden',
  'filter': 'Filter',
  'filter_icon_label': 'Filter',
  'close_drawer': 'Menü schließen',
  'menu_label': 'Menü',
  'home_header_banner_label': 'Startseiten-Banner',
  'app_logo_label': 'App-Logo',
  'legal_icon_label': 'Rechtliches',
  'collapse': 'Einklappen',
  'expand': 'Ausklappen',
  'remove_from_favourites': 'Aus Favoriten entfernen',
  'add_to_favourites': 'Zu Favoriten hinzufügen',
  'previous_image': 'Vorheriges Bild',
  'next_image': 'Nächstes Bild',
  'register': 'Registrieren',
  'login_to_enable_feature': 'Du musst dich zuerst registrieren, bevor du einen Eintrag favorisieren kannst.',

  // Opening hours
  'open_hours': 'Geöffnet ({start} - {end})',
  'closed': 'Geschlossen',
  'opening_hours': 'Öffnungszeiten',
  'weekday': 'Wochentag',
  'time': 'Uhrzeit',
  'monday': 'Montag',
  'tuesday': 'Dienstag',
  'wednesday': 'Mittwoch',
  'thursday': 'Donnerstag',
  'friday': 'Freitag',
  'saturday': 'Samstag',
  'sunday': 'Sonntag',

  // Session
  'session_expired_message': 'Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an.',
  'session_expired_login': 'Anmelden',

  // Calendar
  'add_to_calendar': 'Zum Kalender hinzufügen',
  'calendar_permission_required': 'Kalenderzugriff wird benötigt.',
  'calendar_picker_title': 'Kalender auswählen',
  'calendar_duplicate': 'Termin ist bereits im Kalender vorhanden.',
  'calendar_event_added': 'Termin wurde zum Kalender hinzugefügt.',
  'calendar_no_event_date': 'Kein Veranstaltungsdatum verfügbar.',
};
