Map<String, String> en = {
  "app_name": "{appName}",
  "app" : "App",
  "onboarding_title_1": "App - Whether you are visiting or at home, your ",
  "onboarding_title_2": "{appName} feeling",
  "onboarding_title_3": " starts right here - personalized and full of inspiration.",
  "user_type_selection_title": "This suits me better:",
  "registration_title": "can do more!",
  "password_reset_title": "Forgot Password",
  "remember_password_login_again": "Remember password? Login Again",
  "reset_link_send":"Password reset email sent",
  "login_subtitle": "Log in to {appId} and personalize the app according to your needs.",
  "reset_password": "Reset password",
  "registration_subtitle": "Register for {appId} and personalize the app to suit your needs.",
  "terms_and_conditions_title": "Before you start, please accept our terms of use and privacy policy.",
  "terms_and_conditions_subtitle": "Unfortunately, you cannot use the {appId} app without your consent.",
  "push_notifications_title": "The {appId} app sends you notifications about events in your area, reminds you of saved events and draws your attention to local highlights.",
  "push_notifications_subtitle": "Please confirm that you agree to receive such push notifications.",
  "login_success_message": "Login successful",
  "registration_success_message": "Registration successful",
  "user_type_home": "I am at home here.",
  "user_type_home_info": "Choose this if you want to register. Then you can also save favorites.",
  "user_type_guest": "I am a guest here.",
  "user_type_guest_info": "Choose this if you want to continue without registering and therefore cannot save favorites. You can register later via the settings.",
  "view_terms_and_conditions": "View terms of use",
  "accept_terms_and_conditions": "I have read and accept the conditions.",
  "accept_push_notifications": "I would like to be notified about important information.",
  "decline_push_notifications": "I do not want to receive push notifications.",
  "newsletter_permission": "Want to stay updated? Subscribe to our newsletter!",
  "finish_button": "Finish!",
  "finish": "Finish!",
  "next_button": "next",
  "next": "next",
  "navigate_to_dashboard_warning": "Navigate to dashboard",
  "login_no_account_register": "Don't have an account yet? Register here.",
  "login_already_registered_login": "Already registered? Log in here",
  "welcome_header": "Moin, in the",
  "welcome_description": "App - your personal companion for a real {appName} feeling!",
  "welcome_button": "Let's go!",
  "login_email_label": "Your e-mail",
  "reset_password_email_label": "Your e-mail",
  "login_email_validation_empty": "Please enter an email address",
  "login_email_validation_invalid": "Please enter a valid email address",
  "login_password_label": "Enter Password",
  "confirm_password": "Confirm your password",
  "login_password_validation_empty": "Please enter a password",
  "splash_title": "Find your next\nexperience with",
  "register_firstname_label": "First name",
  "register_firstname_validation_empty": "First name cannot be empty.",
  "register_lastname_label": "Last name",
  "register_username_label": "Username",
  "register_username_validation_empty": "Username cannot be empty.",
  "register_username_validation_length": "Username must be longer than 6 characters.",
  "register_username_validation_whitespace": "Username cannot contain spaces.",
  "register_username_validation_uppercase": "Username cannot contain uppercase letters.",
  "register_email_label": "Your e-mail",
  "register_email_validation_empty": "Please enter an email address",
  "register_email_validation_invalid": "Please enter a valid email address",
  "register_address_label": "Address",
  "register_address_validation_empty": "Address cannot be empty.",
  "register_password_label": "Set a secure password",
  "register_password_validation_empty": "Please enter a password",
  "dashboard_home": "Experience",
  "dashboard_service": "Discover",
  "dashboard_calendar": "Events",
  "dashboard_account": "Profile",
  "dashboard_logout": "Logout",
  "home_events_title": "Events",
  "important_service_title": "Important services",
  "shopping_service_title": "Shopping",
  "administration_title": "Appointment Booking",
  "general_err_message": "Something went wrong!",
  "no_ongoing_events": "No ongoing events",
  "events_search_label": "Search for events in {appName}",
  "show_more_events": "Show all",

  ///semantic labels for images
  "homepage_hero_image_label" : "Photo of {appName} city",
  "event_card_image_label" : "Image of the event",
  "service_tile_image_label" : "Service icon",
  "explore_tile_image_label" : "Discover city image",
  "profile_icon_label" : "User profile icon",
  "home_icon_label" : "Home icon",
  "illustration_related_to_content_label": "Illustration related to the content",
  "main_app_logo": "main {appName} Logo",
  "map_icon_logo": "Map icon logo",
  "search": "Search",
  "no_address": "No address available",
  "open_hours": "open ({start} - {end})",
  "closed": "closed",
  "no_description": "No description available.",
  "weekday": "Weekday",
  "time": "Time",
  "monday": "Monday",
  "tuesday": "Tuesday",
  "wednesday": "Wednesday",
  "thursday": "Thursday",
  "friday": "Friday",
  "saturday": "Saturday",
  "sunday": "Sunday",
  "to":"To",

  // Account Screen
  "account_header": "my.{appNameShort}",
  "account_search_hint": "Search my services",
  "account_section_title": "ACCOUNT",
  "account_my_profile": "My Profile",
  "profile": "Profile",
  "account_app_id": "my{appNameShort}.ID",
  "account_my_applications": "My Applications",
  "account_settings_contact": "Settings & Contact",
  "account_favorites_title": "MY FAVORITES",
  "account_services_title": "MY SERVICES",
  "no_listings": "No listings available",
  "no_data": "No data",
  "see_all": "See all",
  "nearby": "Nearby",
  "error_loading": "Error loading",
  "error_server_unavailable": "Service unavailable. Please try again later.",
  "listing": "Listings",

  //Setting Screen
  "setting": "Settings",
  "language": "Language",
  "accessibility": "Accessibility",
  "privacy_use": "Privacy & Use",
  "notifications": "Notifications",
  "service_offers_configuration" : "Service Offers & Configuration",
  "connections_interfaces": "Connections & Interfaces",
  "chat": "Chat",
  "opening_hours": "Opening Hours",
  "contact": "Contact",
  "app_theme": "Design Adjustments",
  "no_fav_listing": "No favourite listings",
  "navigation_start": "Start navigation",
  "bright": "Bright",
  "dark": "Dark",

  //Filter Screen
  "apply":"Apply",
  "cancel":"Cancel",
  "ok":"OK",
  "t_month":"This Month",
  "l_30d":"Next 30 days",
  "l_7d":"Next 7 days",
  "quick_ranges":"Quick ranges",
  "select":"Select",
  "end_date":"End Date",
  "start_date":"Start Date",
  "reset":"Reset",
  "f_by_date":"Filter by Date",
  "my_profile_data": "MY PROFILE DATA",

  "salutation": "Salutation",
  "first_name": "First name",
  "last_name": "Last name",

  "date_of_birth": "Date of birth",
  "select_date": "Select date",

  "address": "Address",
  "street": "Street",
  "house_number": "House number",
  "zip_code": "ZIP code",
  "city": "City",

  "marital_status": "Marital status",
  "marital_status_select": "Select your current marital status",

  "employment": "Employment",
  "employment_select": "Enter your current employment status",

  "vehicle": "Vehicle",
  "vehicle_owns": "Yes, I own a vehicle.",
  "vehicle_first_registration": "Select first registration",
  "vehicle_license_plate": "License plate",

  "nav_experience": "Experience",
  "nav_discover": "Discover",
  "nav_events": "Events",
  "nav_myapp": "my.{appNameShort}",
  "info": "Info",
  "ok": "OK",
  "eat_and_drinking_title": "Eating & Drinking",
  "coming_soon": "This feature is still under development and will be released soon.",
  "invalid_date_range":"Invalid date range",
  "find_next_experience": "Find your next experience in {appCityName}",
  "terms_of_use":"Terms Of Use",
  "privacy_policy":"Privacy Policy",
  "view_privacy_policy":"View Privacy Policy",
  "imprint":"Imprint",
  "check_connection": "Check your internet connection.",
  "no_internet": "No internet connection.",

  //labels
  "onboarding_buildings_illustration": "Onboarding buildings illustration",
  "app_logo_label": "{appName} app logo",
  "clear_email_tooltip": "Clear email",
  "hide_password_tooltip": "Hide password",
  "show_password_tooltip": "Show password",
  "page_count_label": "Current Page of total Page",
  "user_type_home_card_label": "Select user type as resident, with an illustration of a house.",
  "user_type_guest_card_label": "Select user type as guest, with an illustration of a suitcase.",
  "listing_image_label": "Listing image",
  "back_button_label": "Back",
  "filter_icon_label": "Filter",
  "loading_label": "Loading",
  "close_drawer": "Close drawer",
  "menu_label": "Menu",
  "home_header_banner_label": "Home header banner",
  "app_logo_label": "App logo",
  "legal_icon_label": "Legal",
  "collapse": "Collapse",
  "expand": "Expand",
  "remove_from_favourites": "Remove from favourites",
  "add_to_favourites": "Add to favourites",
  "previous_image": "Previous image",
  "next_image": "Next image",
  "discover_item_label": "View {itemName}",

  "notification":"Notification",
  "push_notification":"Push Notification",
  "notification_service_disabled": "Notification service is not available for this app.",
  "newsletter":"Subscribe the Newsletter",
  "subscribe":"Subscribe",
  "subscribe_request_sent":"Subscription request sent successfully.",
  "favourite_icon_label": "Favourite",
  "common_icon_label": "{itemName} icon",
  "date": "Date",
  'show_all': 'Show all',
  "navigation":"Navigation",
  "location": "Location",
  "delete": "Delete",
  "delete_account_message": "Are you sure you want to delete your account? This action cannot be undone.",
  "delete_account_confirmation": "Delete Account Confirmation",
  "delete_account": "Delete Account",
  "logout_confirmation_message": "Are you sure you want to logout?",
  "restart_required": "Restart Required",
  "language_change_restart_message": "The application needs to restart to apply the language changes.",
  "restart": "Restart",
  "submit": "Submit",
  "not_set": "Not Set",
  "error_start_after_end": "Start date cannot be after end date",
  "register_login": "Register / Login",
  "todays_events": "Today's Events",
  "all_favorites": "All Favorites",
  "blue_line_description" : "The Blue Line connects the train station, ferry terminals, and downtown {appName}.",
  "newsletter_title": "By subscribing to our newsletter, you will receive regular curated updates, city news, and selected event information directly in your inbox.",
  "login_to_enable_feature":"You need to register first before you can favorite a listing.",
  "register":"Register",
  "parking": "Parking",
  "free": "Free ",
  "total": "Total :",
  "no_parking_data_text": "No parking data available",
  "open_maps": "Open Maps",
  "filter": "Filter",
  "book_appointment" : "Book Appointment",
  "ausweise_melde_angelegenheiten": "ID & Registration Matters",
  "zuwanderung": "Immigration",
  "fahrzeug_zulassungen_fahrerlaubnisse": "Vehicle Registrations & Driving Licenses",
  "standesamt": "Registry Office",
  "wohngeld": "Housing Benefit",
  "jugendamt": "Youth Welfare Office",
  "bauaktenarchiv": "Building Records Archive",
  "umweltamt": "Environmental Office",
  "id_registration_matters" : "ID & Registration Matters",
  "immigration" : "Immigration",
  "vehicle_registrations_driving_licenses" : "Vehicle Registrations & Driving Licenses",
  "registry_office" : "Registry Office",
  "housing_benefit" : "Housing Benefit",
  "youth_welfare_office" : "Youth Welfare Office",
  "building_records_archive" : "Building Records Archive",
  "environmental_office" : "Environmental Office",
  "pension_consulting" : "Pension Consulting",
  "appointment_booking" : "Appointment Booking",

  // Profile / Account
  "profile_update_success": "Profile updated successfully",
  "comming_soon": "Coming soon",

  // Listings
  "listingTitle": "Listings",
  "noResults": "No results found",
  "errorTitle": "Something went wrong",
  "retryButton": "Retry",
  "description": "Description",
  "contactInfo": "Contact Information",
  "eventInfo": "Event Information",
  "tags": "Tags",
  "startDate": "Start Date",
  "endDate": "End Date",
  "phone": "Phone",
  "email": "Email",
  "website": "Website",
  "no_languages_available": "No languages available",

  // Session
  'session_expired_message': 'Your session has expired. Please log in again.',
  'session_expired_login': 'Log In',

  // Calendar
  'add_to_calendar': 'Add to calendar',
  'calendar_permission_required': 'Calendar access is required.',
  'calendar_picker_title': 'Select calendar',
  'calendar_duplicate': 'Event is already in the calendar.',
  'calendar_event_added': 'Event added to calendar.',
  'calendar_no_event_date': 'No event date available.',
};
